#!/usr/bin/env bash
# Configure a new Ubuntu server with Nginx and a custom homepage

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.html

service nginx start
